apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-loki
spec:
  # 4am cst
  schedule: "0 4 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            dedicated: master
          tolerations:
          - key: dedicated
            operator: Equal
            value: master
            effect: NoSchedule
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: ghcr-pull-secret
          containers:
          - name: loki-backup
            resources:
              limits:
                cpu: 100m
                memory: 2Gi
            image: ghcr.io/terranblake/backups
            imagePullPolicy: Always
            command: ["python3", "backup.py"]
            env:
            - name: NAME
              value: loki
            - name: FILE_PATH
              value: /data
            - name: FILE_NAME
              value: loki
            - name: HEALTHCHECK_UUID
              value: 4c94c72f-b4ed-4b32-9b9e-014fd4c15bdc
            - name: PARENT_FOLDER
              value: 17lRsV33XYch5rYKE2vpOx2AGZgNh_hq-
            - name: HEALTHCHECK_ENDPOINT
              value: https://hc-ping.com/
            - name: REFRESH_PATH
              value: /usr/config/refresh/gdrive.pickle
            - name: CREDENTIALS_PATH
              value: /usr/config/credentials/gdrive.json
            volumeMounts:
              - name: refresh
                mountPath: /usr/config/refresh
                readOnly: false
              - name: credentials
                mountPath: /usr/config/credentials
                readOnly: false
              - name: data
                mountPath: /data
          volumes:
            - name: refresh
              configMap:
                name: gdrive-refresh
            - name: credentials
              configMap:
                name: gdrive-credentials
            - name: data
              hostPath: 
                path: /opt/loki
                type: Directory
