apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-minecraft
spec:
  # 4am cst
  schedule: "0 7 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            dedicated: master
          tolerations:
            - key: dedicated
              operator: Equal
              value: master
              effect: NoSchedule
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: ghcr-pull-secret
          initContainers:
            - name: minecraft-backup
              resources:
                limits:
                  cpu: 300m
                  memory: 4Gi
              image: ghcr.io/terranblake/backups
              imagePullPolicy: Always
              command: ["python3", "backup.py"]
              env:
                - name: NAME
                  value: minecraft
                - name: FILE_PATH
                  value: /data
                - name: FILE_NAME
                  value: minecraft
                - name: HEALTHCHECK_UUID
                  value: 5bc35dad-cac5-4d4b-bb05-3c1fbf689be9
                - name: PARENT_FOLDER
                  value: 17lRsV33XYch5rYKE2vpOx2AGZgNh_hq-
                - name: HEALTHCHECK_ENDPOINT
                  value: https://hc-ping.com/
                - name: REFRESH_PATH
                  value: /usr/config/refresh/gdrive.pickle
                - name: CREDENTIALS_PATH
                  value: /usr/config/credentials/gdrive.json
              volumeMounts:
                - name: refresh
                  mountPath: /usr/config/refresh
                  readOnly: false
                - name: credentials
                  mountPath: /usr/config/credentials
                  readOnly: false
                - name: data
                  mountPath: /data
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command: ['kubectl', 'rollout', 'restart', 'deployment/minecraft', '-n', 'minecraft']
          volumes:
            - name: refresh
              configMap:
                name: gdrive-refresh
            - name: credentials
              configMap:
                name: gdrive-credentials
            - name: data
              hostPath:
                path: /opt/minecraft
                type: Directory
