apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-minecraft
spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            dedicated: master
          tolerations:
          - key: dedicated
            operator: Equal
            value: master
            effect: NoSchedule
          containers:
          - name: backup
            image: alpine
            args:
            - /bin/sh
            - -c
            - apk add --no-cache curl lftp;
              export TS=$(date +%s);
              mkdir -p /temp/data/;
              cp -r /data/* /temp/data;
              tar -cvf minecraft_$TS.tar /temp/data;
              rm -rf /temp/data;
              lftp -u ${USER},${PASSWORD} 192.168.1.228 -e "put -O /home/cluster/ftp/backups minecraft_$TS.tar;
              curl https://hc-ping.com/5bc35dad-cac5-4d4b-bb05-3c1fbf689be9;
              bye"
            env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: ftp-credentials
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ftp-credentials
                  key: password
            volumeMounts:
            - name: data
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: data
            hostPath: 
              path: /opt/minecraft
              type: Directory
