apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: kube-system
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command:
        [
          "/bin/sh",
          "-c",
          "env"
        ]
      envFrom:
        - secretRef:
            name: oauth2-creds
