apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: default
  labels:
    app: grafana
spec:
  storageClassName: manual
  volumeName: grafana-pv
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi