apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minecraft-cac
  name: minecraft-cac
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-cac
  template:
    metadata:
      labels:
        app: minecraft-cac
    spec:
      # only allow minecraft to run on the master which is expected to always have a physical drive attached
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: mc2
          hostPort: 
          image: ghcr.io/terranblake/minecraft-server
          env:
          - name: TZ
            value: "America/Chicago"
          - name: LEVEL_TYPE
            value: "DEFAULT"
          - name: ALLOW_FLIGHT
            value: "true"
          - name: OVERRIDE_SERVER_PROPERTIES
            value: "TRUE"
          - name: MOTD
            value: "By joining you accept the terms of service -> "
          - name: DIFFICULTY
            value: "hard"
          - name: EULA
            value: "true"
          - name: TYPE
            value: VANILLA
          - name: VERSION
            value: LATEST
          # needed for Paper versions before 1.14
          - name: CONSOLE
            value: "false"
          - name: ICON
            value: "https://i.imgur.com/K21cDtl.png"
          - name: OVERRIDE_ICON
            value: "TRUE"
          - name: ENABLE_AUTOPAUSE
            value: "TRUE"
          - name: OPS
            value: SuperKi64,tblake_kansas
          ports:
            - name: http
              containerPort: 25565
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /opt/caves-cliffs-1.17
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: minecraft-cac
  name: minecraft-cac
  namespace: minecraft
spec:
  ports:
    - port: 25566
      targetPort: 25565
  selector:
    app: minecraft-cac
  type: LoadBalancer