apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-pvc
  namespace: earney
  labels:
    app: superset
spec:
  storageClassName: manual
  volumeName: superset-pv
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi