#!/bin/bash

# In order to get an IPv6 lease from online.net
# sysctl -w net.ipv6.conf.enp1s0.accept_ra=2

###########################
# IPv4
###########################

# todo: use ufw for firewall management
# sudo ufw allow 51194/udp

# Turn off the firewall. Only forwarded ports will ever be able
# to reach the cluster, so we _should_ be safe from any unwanted behavior
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT


# ###########################
# # IPv6
# ###########################
# # Reset our custom chain
# ip6tables -P INPUT ACCEPT
# ip6tables -D INPUT -j USER_CUSTOM
# ip6tables -F USER_CUSTOM
# ip6tables -X USER_CUSTOM

# ip6tables -N USER_CUSTOM

# # Allow loopback interface
# ip6tables -A USER_CUSTOM -i lo -j ACCEPT

# # Allow wireguard interface
# ip6tables -A USER_CUSTOM -i wg0 -j ACCEPT

# # Allow Kubernetes interfaces
# ip6tables -A USER_CUSTOM -i cni0 -j ACCEPT
# ip6tables -A USER_CUSTOM -i flannel.1 -j ACCEPT

# # Allow already accepted connections
# ip6tables -A USER_CUSTOM -p tcp  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
# ip6tables -A USER_CUSTOM -p udp  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
# ip6tables -A USER_CUSTOM -p icmp -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# # Accept incoming ICMP
# ip6tables -A USER_CUSTOM -p icmpv6 -j ACCEPT

# # Allow ipv6 route configuration
# ip6tables -A USER_CUSTOM -p udp --dport 546 -j ACCEPT
# ip6tables -A USER_CUSTOM -p icmpv6 --icmpv6-type router-advertisement -j ACCEPT
# ip6tables -A USER_CUSTOM -p icmpv6 --icmpv6-type router-solicitation -j ACCEPT
# ip6tables -A USER_CUSTOM -p icmpv6 --icmpv6-type neighbour-advertisement -j ACCEPT
# ip6tables -A USER_CUSTOM -p icmpv6 --icmpv6-type neighbour-solicitation -j ACCEPT 
# ip6tables -A USER_CUSTOM -p icmpv6 --icmpv6-type echo-request -j ACCEPT
# ip6tables -A USER_CUSTOM -p icmpv6 --icmpv6-type echo-reply -j ACCEPT

# # Allow ssh
# ip6tables -A USER_CUSTOM -p tcp --dport 22 -j ACCEPT

# # Allow http/https
# ip6tables -A USER_CUSTOM -p tcp --dport 80 -j ACCEPT
# ip6tables -A USER_CUSTOM -p tcp --dport 443 -j ACCEPT

# # Allow SMTP and IMAP
# ip6tables -A USER_CUSTOM -p tcp --dport 25 -j ACCEPT
# ip6tables -A USER_CUSTOM -p tcp --dport 993 -j ACCEPT

# # Allow wireguard
# ip6tables -A USER_CUSTOM -p udp --dport 995 -j ACCEPT

# # Allow kubernetes
# #ip6tables -A USER_CUSTOM -p tcp --dport 6443 -j ACCEPT


# # Add our custom chain
# ip6tables -I INPUT 1 -j USER_CUSTOM

# # DROP INCOMING TRAFFIC by default
# ip6tables -P INPUT DROP
