apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: earney
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # this is not inteneded to stay this way. there are issues using hostPath with k3s to provision
      # volumes, so temporarily, this service has full rw access to the volume mounted under the name data
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: postgres
          image: bitnami/postgresql
          envFrom:
          - secretRef:
              name: postgres-creds
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: postgres-creds
          secret:
            secretName: postgres-creds
        - name: data
          hostPath:
            path: /var/lib/postgresql/data
            type: Directory
          # persistentVolumeClaim:
          #   claimName: local
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: earney
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    name: postgres
    targetPort: 5432
  selector:
    app: postgres