apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: earney
  name: deployer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer
  namespace: earney
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: earney
roleRef:
  kind: Role 
  name: deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  labels:
    app: webhook
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: deployer
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
      - name: webhook
        image: ghcr.io/terranblake/webhook:latest
        imagePullPolicy: Always
        args:
        - "-hooks=/data/hook.json"
        - "-http-methods=POST"
        - "-port=8085"
        - "-verbose"
        - "-hotreload"
        ports:
        - containerPort: 8085
        volumeMounts:
        - name: config
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: webhook
          defaultMode: 0777

---
apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  selector:
    app: webhook
  ports:
    - protocol: TCP
      port: 8085
      name: http
  clusterIP: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webhook-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - hooks.terranblake.com
    secretName: webhook-tls
  rules:
  - host: hooks.terranblake.com
    http:
      paths:
      - path: /
        backend:
          serviceName: webhook
          servicePort: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook
data:
  hook.json: |
    [
      {
        "id": "deploy",
        "execute-command": "/data/deploy.sh",
        "command-working-directory": "/var/run/",
        "pass-arguments-to-command":
        [{
          "source": "payload",
           "name": "application_name"
        }],
        "trigger-rule": {
          "match": {
            "type": "value",
            "value": "__DEPLOYER_SECRET__",
            "parameter": {
              "source": "header",
              "name": "X-Webhook-Token"
            }
          }
        }
      }
    ]

  deploy.sh: |
    #!/bin/sh
    
    [[ -z "$1" ]] && exit 1

    kubectl delete pod -n default -l app=integrator
    kubectl wait --for=condition=Ready --timeout=-1s -n default -l app=integrator pod

    kubectl delete pod -n default -l app=scheduler
    kubectl wait --for=condition=Ready --timeout=-1s -n default -l app=scheduler pod

    kubectl delete pod -n default -l app=server
    kubectl wait --for=condition=Ready --timeout=-1s -n default -l app=server pod
