apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: earney
  labels:
    app: redis
spec:
  storageClassName: manual
  volumeName: redis-pv
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi