name: Publish Superset Image
on:
  push:
    paths:
    - 'superset/**'
   
jobs:
  buildAndPush:
    name: Build And Push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Superset
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: superset
          file: superset/Dockerfile.superset
          push: true
          tags: ghcr.io/terranblake/superset:latest
      - name: Superset Image digest
        run: echo Superset ${{ steps.docker_build.outputs.digest }}
      - name: Trigger deployer
        run: |
          payload='{ "application_name": "superset", "image_digest": "${{ steps.docker_build.outputs.digest }}", "image_tag": "latest" }'
          token='X-Webhook-Token: ${{ secrets.WEBHOOK_SECRET }}'
          curl -i -X POST -H 'Content-Type: application/json' -H "${token}"  -d "${payload}" https://hooks.terranblake.com/hooks/deploy
