apiVersion: ENC[AES256_GCM,data:bjc=,iv:V9GMy10FRyYMT2B1GYfpvOhZZls6V+U2gMBX4mbDeQk=,tag:NwgmKpWbNOEpK7SRPDpcJQ==,type:str]
kind: ENC[AES256_GCM,data:/1yXCzuA,iv:gs0LvdSFo4HAJYcQUvZhktf80L9/U0ESbZuQZVWDDd4=,tag:4EZnu/6foVLfXGshb/chgQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lHJAA7WBIyRSE/G0eCQMTfGtKjgtkpEJtqYg,iv:ZmOQh+aE/QNY3AflDIzP9ohIRjgdcUURteDOHwQbem4=,tag:kuCHZrM3idj9Pp6Pb3KS5Q==,type:str]
    namespace: ENC[AES256_GCM,data:PjG+tp/D+il7/anM,iv:lzB6HfDjnE9n7TI3LQLDAjCfiH30CodqrlGNWeyNdOA=,tag:0vpwXjNc5kOHjEDU1oWPpA==,type:str]
type: ENC[AES256_GCM,data:+gF/sf8e,iv:TkPnr3KJn5ERzPAU06OOHfkH9oGQ9M8j8MCVG3X5+Vw=,tag:SRWIHKnF4D1kklqcjMh+Cw==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:MSusR1F+tdf8bFYL0rLYTJxhc9iHvQCwy/wUdbTP8tloi+OvhD8Tmg==,iv:6BFutwYSVAVOAXbf/C1ErB6Gte5/KMjmXcvtPfXQ0Zs=,tag:+3J4dCfzpRzKhrUM9xp56A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-18T15:54:49Z'
    mac: ENC[AES256_GCM,data:KgfhXJkXQqsFNwa5LTKNYQ1hdrS/AzWj6CbtGjJCGemWfYR7lR5YJOaF95ZfHRMCFkE26A7uHg+vDxBqtV1H/rU+SZgdd0Hk/ZTOqxkHs8YqqCyiv05cHTkwsairRA+W7uTcgnyOlev4UCinWPcftegkDWcafj63Hn53ohUse2g=,iv:fpJVnjfUYZUdGl53BopiVpGsAd0rPDZYCdVYfluzkIY=,tag:qMjEDm/MX6zOZoxHBg1whA==,type:str]
    pgp:
    -   created_at: '2020-12-18T15:54:49Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA599Kw2RwhXKAQf/RzDIzHApjYpqGsk5asFE2IfLNfmssFs9vIzvXA2yd0NO
            5u5ePb4X20E7S5XhA38w6dfOn4RykSK/WfmSWRkBfJZPlCXU+9i69hc03r2aY65R
            dkZ+Yvp769pSRfl2VYlJVfQBiAasRBuut1ZNC02Ulb+brukBIKlaNGDkNp9kHQAF
            hDaZrx7xCjvonnpIS3SgLkif2ekqvLepZn5WXtqG9wjmEs+oaQ+HwEvXhXl1Dzjr
            NsgpaLm63CvON1s49p7c0cZ+bFPGnCTp4wKdAZ0sS2YHy5W6okb8wVbqg9NXwgFW
            8gvqwajW08plGELY64wPb3z/YbkxWNappnIg7Oa8gdJeAYLUgyji6YsoiDu2uX6N
            5oGvSq9Zf2LDmq0qjqm+5ikKTN0ARatKi4jSR/0Y4GQn3NaSaGjIYNJ8hfs6/cVz
            wyKkyQKz9Rh0Wd3TZohXxuIj1UhWtavcD0RurolGWA==
            =dmKH
            -----END PGP MESSAGE-----
        fp: 302410BC10AF18C9AEA5BF6F6DBFAEDF5D191988
    unencrypted_suffix: _unencrypted
    version: 3.6.1
