apiVersion: ENC[AES256_GCM,data:Ahw=,iv:wlpui5P/d4O7sX3sQQS4f5x393B4KYcFlexP7/kZs0k=,tag:hm7IFvEfIUWynVw7AsdD+A==,type:str]
kind: ENC[AES256_GCM,data:o2/CUSk5,iv:X69GJCuvsWHRw7ZEy6OCAXtyEOOy7CrnhlhXSn7R5WA=,tag:6Hh68/BXKZgYQ7wmGiseIw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qQSvY7Pw9g==,iv:tv6J6ivvuZ75dFIK9xMhIPh0ZqQB3vBWluMoFh4Ix+0=,tag:Pvhn0b7BeJcavnizGXLpBw==,type:str]
    namespace: ENC[AES256_GCM,data:TILXA92QEg==,iv:VWbk5HGm6Ya2UQbZ4xG1p02hC7/xVE2+dg2uZqkwYeQ=,tag:ABpFhxagKKCHXOc/M0botw==,type:str]
type: ENC[AES256_GCM,data:a+r44ePN,iv:qFdZ2KaDQkD/P0moG3sQKMYF636jgspDc5j6qsgkxYo=,tag:1OWFF9GibkAXbaECVcuomw==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:AugCB/I=,iv:GMu9lsEZIcq93qnaGoyDjazqB8a+ribNCXqbFEi+b04=,tag:bISjVFAT51PMa9BIcrtyCg==,type:str]
    admin-password: ENC[AES256_GCM,data:mbJkaqMLZbZQPddYJy6dssm7WA==,iv:CFY4H4n14BzEV7kjtvO89fAnqy8ITaV++y05SXMiFYo=,tag:T5j5eSem0J0/q7l3VNYaSw==,type:str]
    ldap-toml: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-03T22:57:27Z'
    mac: ENC[AES256_GCM,data:VCoY02oQX1eHfBnP9gqR5d2ZNysJiBEXOihHGHo0mRyo1uyoolL94PW/H/lnwsK7WHFV8FTxkfpJyg9nvJxOm/X0Rrd1TQPSJip+4bK70uIfuhbczzcwgHAl9N7N6k0oNbnx/PilvRjv6zvPkt6wvWT3bhD9wEVSC6Buq50CWgw=,iv:6w+IOQsbiK+gU7sd2x/6Mg8PwwCJLhzYdjCnWZactAw=,tag:GHQ7SuujYjdc7gKYTwhR1w==,type:str]
    pgp:
    -   created_at: '2021-03-03T22:57:26Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA599Kw2RwhXKAQgAiHs1F47eZFolcNeJK899i715xAB+rxco8HFK/lQR8k4T
            jC6STX5NFtH+McuqpbgmuJi2/xoxrLXQc1YdknEdPjrMdVHHG8VEbMa/ffIUBt2l
            ycR6wnKMRi5QCBF6+sVbbG9BFEMOZqExo8pugFvwqGeqadlmrPF0Ki5ssVqQG6Yq
            v0omL+PnbLucdX6AjAcbFIMv/lwqnmtYei/vRUi4xHC9x0Wsgh+2Xu/mUM5EnKtL
            d9sp2HUL1t770c7nYzEiKSDyZdSC4lF3Je7hlH3EYglK5Jf2PAmJdjtIVwOC8IuE
            F5EGz6JMsevLWpPEyy+aBSKSxcH5uaZUxei75Fc0PtJeAUWjz2dgrJCg8ZslVcyx
            owsa8LzbRhN/6qsB8kR5LMpvTbryqWe1SRjCZEScTBVRb4JkoBAxCAGB9HBMenvZ
            t4EBrhNm/GfB7/Fvmgxf6mjPQggxalOCYO49ECAJEQ==
            =JxQd
            -----END PGP MESSAGE-----
        fp: 302410BC10AF18C9AEA5BF6F6DBFAEDF5D191988
    unencrypted_suffix: _unencrypted
    version: 3.6.1
