apiVersion: ENC[AES256_GCM,data:NDw=,iv:C/B6GxLtcf49UuGSGPiLx6H6qGFTi88XW8AJJV1dSGU=,tag:2t8a0kzDXcvpc9l0ttALcQ==,type:str]
kind: ENC[AES256_GCM,data:Da1m0RhU,iv:QLInudffSyhsykqVZctCteuZIUN/YgNsubAIjjiFJdY=,tag:506p0q6vSchj0u76O3ZK5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wbdBog==,iv:40qNx1t1VPNoiyvf0yiO58I/5zsuVFf1ORDW6hPOPq0=,tag:T6kZU2prju2Qiwx06tuu2Q==,type:str]
    namespace: ENC[AES256_GCM,data:96iEkMxn9w==,iv:/cDSV+oxyBunjJX1Tjuz0mVSY2rF+tmXam8bZ1Dmvus=,tag:tLPu3cuA5GenjhmQw6GM1A==,type:str]
    labels:
        app: ENC[AES256_GCM,data:TCiqhQ==,iv:Cs7/TFWWNXmNFHRPv9MuUoMKh2KtKUwMiGz9bx2ORPc=,tag:bIK7xqbkiePplCCU91Y3Og==,type:str]
        chart: ENC[AES256_GCM,data:IJ5FSJgRht1JWg==,iv:GUUZLNQzfLLvsy68BEgegPLQJrMbdLKGl71K4sEE0fc=,tag:G2gizyefNwxXmVLHBwp2DQ==,type:str]
        release: ENC[AES256_GCM,data:0FcKCg==,iv:ktWqxeYX22nWLqMOVSzrgLyHfnxDbpYDgmGBLQZI9Cw=,tag:MKj/NO9ggBtqIaf1bvllIg==,type:str]
        heritage: ENC[AES256_GCM,data:xvWLSw==,iv:aupbjn2HIrVn4Zm4tshY+P+oo6E20W/4KXMkbqG9mJw=,tag:81vvnWFTsDdiZfrjNB7u6w==,type:str]
data:
    loki.yaml: ENC[AES256_GCM,data:t8JsId+9FgqbFHJxDExef/Y6RA2cmWer1P3RbiRR2aEXnV/nKHN+QAyNi8o0kYDsmol+SPWvPR9Ejm4+l3BXJHXMhPeKR4BpjQb9MgpUOn1Yf5eXNHUSSutlSlx4kXa+cAvg2y1CdSY/a+liFEkpBRP0lpnYfpncfXv+r3gSiexpKfr+WnNs7YqUrDWuM8UJHBWg2VEmCvVrMRWGwBhtnwsVxQoCIXRHNhirjpVnIMk5aLDCXnU9iYKFEqNWzcgsDDdyMXP975A1/Bw9oJyTL2PdfINfV31Isf90SBhe9LBNK9h81k3p3S5qgL8wOWGbHsr9Fkr7LClyJUvTxaiWWYyjNQxUDyheYPTZ1qJByYqH8CtzjJkTFZLSV1+nfopzd50lk943toxgKMuoTJp1ox9dg1oid2TvotqyGtq+KQ62Y3mYrn9M3+wbFFRFViZhPdqqKuM8q28ZDXlzyiIpWm9p7sBo4MvNSm0dT2jWJ+3fWD4aU5aGgfWGOdVKTtzB8lNUGpa+vyMJKJ5QS5Z/E1jf4PTj1bDufFEmZ1MFmKPoHvDtbIkWTjfpNWWx7gcUgEvKHMDW6hVycPC4cusj632JbFrc44Gd7JfTcLNv1Ax71VtRHDZoQNYuXALVsyw8Qeps97HRU4nyOGaxTjvFRPIALCvCcyqUB9qpsLYNsqzF4Z9l4EToHNaWooiB2jat4lKNNylvzesnKboryTko9zymxNytnJNweQLFSUnwQsSPjXlgO8uAlilkWJblDhoT7KbR+oHlVpKojhKqV9AT/KV8S4VLWuJfgiCjEwPgAUaKX5bhj0wcN8yu9Yrx1ERLcEHj6rDZzvYUlsXHLO60kz88ZECQqhDnpEDVb+EattXKLS+II0uss+qdlKgvUeNmwtsHmlO9HBu0AVmXJLF/V8GifzyHilbbR5QSKYOtGb0MuyuxvEbrVkm3gD15slynMKU9EwuuEDrszlQjKRWhjzGatJbnZm6aTXSxzNnc6wt91dQDw+nJvtY627W4WYWhbikovUwnmv6rKNbjCHbD4oXIMkDqyTGF/AMvmhmY8E96C7gmtyb/qwNXX6smT88spc3TeO5xW6IiWuEEtML9zZX+rnPd5FtF7bWVSf/Zn9bK+70t1HfgfzrakmKW13u1m1th/jCRG+aiMXqm1pYPxOxtPuuFfUlBAZuY/w0Qxt13OC4JWK4PXcsTL7tpiv3+RtLWybq+i7lWx7DcP8gZ1sLR7NYa8qT3sZ1cqFYxk7guAf8ksLoJeUliHqyPlYOzZogsqG/dpsrLGvjMQwCRc/AmjMZwd+5Jtq1B+FM2bT1I2VSTMdGiJiZ5VGSIVvbdZhRpJLFh8UdbXhTeFnDRX2BPv10UB3/n4O8CUUCHrx3VgVDXtYGPPyqNVGdIjMRvexHQrH/5q92mMSgZKpAv5l6Bel29Q+fcpYL+q+pdWx9zofhDwE2btzcJIy3iatevKNAQliFtsQnhP5hxc/RRxiRcAclSnuFdLaM5S90tWQ7idoxmjptT6AkuJ/0xUOD3BvjtyuZSHx729RKPi2CoL7hbxanCJ2r3jzp/9+ZvW5hGjLGwQA4AW3gHJQMu9X+rUhAXJUIVHjZHY+cFUlWK8e01H9UXqjQBwtZMSCqFcyIAD3d+Nivl9JhlsMPI0zFS1dt2ExKh9s2Gju/Psul4ysmTQf8H+6KfiJn0kQ4Keh+fHpjfr6cbrM1K/VVyopYC8kIbNZd1nXPM/A+bzAwIXzPHNH2M3xUb,iv:0the2a0MaLMJyqw3t2N2WIPtYpHh07AijGGnejHZtjE=,tag:8xn6eahW+MIMLq1OKyHJ+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-15T23:27:16Z'
    mac: ENC[AES256_GCM,data:4r6sNq0gN1WJrbqOe50e364i7wTlDBrpuuq+H/H/OJIvo0F4+Zv1Iq2haX/q/wzJq8ZvFQG4MuRDLm4ApyImq/eefg/qjzBtEoZuj02sVEW4PcwopKRMJ6MnW5yVSA+1PLZkmhKJ62HA/wEFpo7p+2HDTSmwBWGIG+GlbMdw/28=,iv:Le58Io/agmFLNkZ8D+gbo9B74ED/HcN+w4ydJdJe8yw=,tag:HGHIKENDL15SJK/AfPVJDQ==,type:str]
    pgp:
    -   created_at: '2021-03-15T23:27:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA599Kw2RwhXKAQf+LFDAa8R3qG6HzQLpfThOOx6yUpro1CdF5XnuN5A+eiW+
            aIqmVSgcnXk3JA0n4un4pUlyM7tFMDuBuMKYwb08PEW8vseY9MoZveTzkie3iXAT
            JM5jQMnuAWxMcoJYkqO3D4zgML+S8ZpcY+NMluKdGRx8XOc3vpiuPXDt8SXr34N7
            P91+oiTkUatqPFTyQJOA3AS/KbmBJPSteJepIXtmSs/dEUJretyczF93SdBsi9rW
            P3iYSqhYuq6+g/rGNRim+8Barjp2VQ8iIlUdZPTUBZWO4hq+MvfoWmt8g5Tc7pJe
            GBUzrisZ7dr6TqGf4vMLFJa3ZintvJ6duAPhxEuOFNJcAS2XJAMxRa1KcAOneNzd
            MqeLckzmYputrB09gRVL20/QbGiPJCxo9tbdBjTbbNySwlADrUvJQEWdXcFwaNxx
            JnckUL02K4Wl+u/HHeB42pcbcwVAqsCExt7GQQU=
            =g2Gk
            -----END PGP MESSAGE-----
        fp: 302410BC10AF18C9AEA5BF6F6DBFAEDF5D191988
    unencrypted_suffix: _unencrypted
    version: 3.6.1
